Repository anoma/namada-interface, pull requests merged in 2022-10, with the labels that each got.

#100 fix(theme, colors): theme changes to dark after refreshing the app
  apps/namada-interface/src/App/App.tsx
  apps/namada-interface/src/App/TopNavigation/topNavigation.tsx
  apps/namada-interface/src/App/TopNavigation/topNavigationLoggedIn.tsx
  apps/namada-interface/src/App/types.ts
  apps/namada-interface/src/utils/theme/index.ts
  apps/namada-interface/src/utils/theme/theme.ts
Labels: C - Bug, Wallet UI

#103 refactor(theme, colors): replace isLightMode with colorMode in regular components
  apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
  apps/namada-interface/src/App/App.components.ts
  apps/namada-interface/src/App/App.tsx
  apps/namada-interface/src/App/Settings/SettingsAccountSettings/SettingsAccountSettings.tsx
  apps/namada-interface/src/App/Settings/SettingsWalletSettings/SettingsWalletSettings.tsx
  apps/namada-interface/src/App/TopNavigation/topNavigation.components_delete.ts
  apps/namada-interface/src/App/TopNavigation/topNavigation.tsx
  apps/namada-interface/src/App/TopNavigation/topNavigationLoggedIn.tsx
  apps/namada-interface/src/utils/theme/index.ts
  apps/namada-interface/src/utils/theme/index_delete.ts
  apps/namada-interface/src/utils/theme/theme.ts
  apps/namada-interface/src/utils/theme/theme_delete.ts
Labels: C - Refactoring, Wallet UI

#107 refactor(theme, colors): add colorMode to the styled components
  apps/namada-interface/src/App/AccountCreation/AccountCreation.components.ts
  apps/namada-interface/src/App/AccountOverview/AccountOverview.components.ts
  apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.components.ts
  apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
  apps/namada-interface/src/App/App.components.ts
  apps/namada-interface/src/App/App.tsx
  apps/namada-interface/src/App/Token/TokenSend/TokenSend.components.ts
  apps/namada-interface/src/App/Token/TokenSend/TokenSendForm.tsx
  apps/namada-interface/src/App/TopNavigation/topNavigation.components.ts
  apps/namada-interface/src/App/TopNavigation/topNavigationLoggedIn.components.ts
  apps/namada-interface/src/components/Button/button.components.ts
  apps/namada-interface/src/components/ButtonTemporary/button.components.ts
  apps/namada-interface/src/components/ButtonTemporary/button.tsx
  apps/namada-interface/src/components/ButtonTemporary/index.ts
  apps/namada-interface/src/components/Image/image.tsx
  apps/namada-interface/src/components/Input/input.components.ts
  apps/namada-interface/src/components/NavigationContainer/NavigationContainer.tsx
  apps/namada-interface/src/components/Select/Select.components.ts
  apps/namada-interface/src/components/Toggle/toggle.components.ts
  apps/namada-interface/src/utils/theme/index.ts
  apps/namada-interface/src/utils/theme/theme.ts
Labels: C - Refactoring, Wallet UI

#112 feat: notifications
  apps/namada-interface/src/App/AccountOverview/AddAccount.tsx
  apps/namada-interface/src/App/App.tsx
  apps/namada-interface/src/components/Toast/index.ts
  apps/namada-interface/src/components/Toast/toast.components.ts
  apps/namada-interface/src/components/Toast/toast.tsx
  apps/namada-interface/src/slices/AccountsNew/actions.ts
  apps/namada-interface/src/slices/index.ts
  apps/namada-interface/src/slices/notifications.ts
  apps/namada-interface/src/store/mocks.ts
  apps/namada-interface/src/store/store.ts
Labels: C - Feature, Wallet UI

#84 feat/61 - Extension: Authentication
  apps/extension/src/App/Accounts/AccountListing.components.ts
  apps/extension/src/App/Accounts/Accounts.components.ts
  apps/extension/src/App/Accounts/Accounts.tsx
  apps/extension/src/App/Accounts/AddAccount.tsx
  apps/extension/src/App/Accounts/index.ts
  apps/extension/src/App/App.components.ts
  apps/extension/src/App/App.tsx
  apps/extension/src/App/Loading/Loading.components.ts
  apps/extension/src/App/Loading/Loading.tsx
  apps/extension/src/App/Loading/index.ts
  apps/extension/src/App/LockWrapper/LockWrapper.components.ts
  apps/extension/src/App/LockWrapper/LockWrapper.tsx
  apps/extension/src/App/LockWrapper/index.ts
  apps/extension/src/App/Login/Login.components.ts
  apps/extension/src/App/Login/Login.tsx
  apps/extension/src/App/Login/index.ts
  apps/extension/src/App/Setup/Setup.tsx
  apps/extension/src/App/Setup/index.ts
  apps/extension/src/App/index.tsx
  apps/extension/src/App/types.ts
  apps/extension/src/background/keyring/handler.ts
  apps/extension/src/background/keyring/init.ts
  apps/extension/src/background/keyring/keyring.ts
  apps/extension/src/background/keyring/messages.ts
  apps/extension/src/background/keyring/service.ts
  apps/extension/webpack.config.js
  packages/components/src/Input/input.tsx
  packages/crypto/README.md
  packages/crypto/lib/Cargo.lock
  packages/crypto/lib/Cargo.toml
  packages/crypto/lib/src/crypto/bip32.rs
  packages/crypto/lib/src/crypto/bip39.rs
  packages/crypto/lib/src/crypto/mod.rs
  packages/crypto/src/__tests__/crypto.test.ts
Labels: C - Feature, Extension UI, Extension Core

#115 feat(button): create button with spinner
  apps/namada-interface/src/App/Login/Login.tsx
  apps/namada-interface/src/components/Button/button.components.ts
  apps/namada-interface/src/components/Button/button.tsx
Labels: C - Feature, Wallet UI
