Repository anoma/namada-interface, pull requests merged in 2023-02, with the labels that each got.

#197 specs/196 - Bring interface & extension specs up-to-date
  specs/browser-extension/architecture.md
  specs/browser-extension/integration.md
  specs/browser-extension/interface.md
  specs/browser-extension/key-management.md
  specs/browser-extension/overview.md
  specs/browser-extension/session.md
  specs/browser-extension/storage.md
  specs/interface/ibc.md
  specs/interface/overview.md
  specs/interface/rpc.md
  specs/interface/shielded-transfers.md
  specs/interface/transparent-transactions.md
  specs/packages/overview.md
  specs/web-wallet/client-application.md
  specs/web-wallet/interface-technical-specifications.md
  specs/web-wallet/key-derivation.md
  specs/web-wallet/persistence.md
  specs/web-wallet/rpc.md
Labels: C - Documentation

#207 feat: add validation for address alias
  apps/extension/src/App/Accounts/AddAccount.components.ts
  apps/extension/src/App/Accounts/AddAccount.tsx
Labels: C - Feature, Extension UI

#210 refactor/sdk-cleanup
  apps/extension/src/background/index.ts
  apps/extension/src/background/keyring/keyring.ts
  apps/extension/src/provider/Anoma.test.ts
  apps/extension/src/test/init.ts
  packages/shared/lib/src/rpc_client.rs
  packages/shared/lib/src/sdk.rs
  packages/shared/lib/src/sdk/masp.rs
  packages/shared/lib/src/sdk/mod.rs
  packages/shared/lib/src/sdk/tx.rs
  packages/shared/lib/src/sdk/wallet.rs
  packages/shared/lib/src/utils.rs
Labels: C - Refactoring

#215 Bug/214 -Fix build command in extension
  apps/extension/package.json
Labels: bug

#209 Keplr Integration - Display All Accounts
  apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.components.ts
  apps/namada-interface/src/App/AccountOverview/DerivedAccounts/DerivedAccounts.tsx
  apps/namada-interface/webpack.config.js
  packages/chains/src/chains/cosmos.ts
  packages/chains/src/chains/osmosis.ts
  packages/integrations/package.json
  packages/integrations/src/Anoma.ts
  packages/integrations/src/Keplr.ts
  packages/integrations/src/Metamask.ts
  packages/integrations/src/types/Integration.ts
  packages/types/src/tx/types.ts
Labels: T- Integrating 3rd Party Extensions, IBC transfer
