Repository anoma/namada-interface, pull requests merged in 2023-07, with the labels that each got.

#310 feat/264 - Handle third-party extension events
  apps/namada-interface/src/services/extensionEvents/handlers/keplr.ts
  apps/namada-interface/src/services/extensionEvents/handlers/metamask.ts
  apps/namada-interface/src/services/extensionEvents/provider.tsx
  packages/chains/src/index.ts
  packages/hooks/src/useEvent.ts
  packages/types/src/events.ts
Labels: C - Feature, Wallet UI

#329 bug - Fix for crash on event registration
  apps/namada-interface/src/services/extensionEvents/provider.tsx
Labels: bug

#325 refactor: amounts improvements
  apps/extension/package.json
  apps/extension/src/background/approvals/service.ts
  apps/extension/src/background/keyring/keyring.ts
  apps/extension/src/provider/Anoma.test.ts
  apps/extension/src/provider/Signer.ts
  apps/extension/tsconfig.json
  apps/namada-interface/tsconfig.json
  package.json
  packages/crypto/tsconfig.json
  packages/integrations/src/Anoma.ts
  packages/integrations/tsconfig.json
  packages/shared/lib/src/sdk/tx.rs
  packages/types/package.json
  packages/types/src/tx/messages/index.ts
  packages/types/src/tx/schema/account.ts
  packages/types/src/tx/schema/bond.ts
  packages/types/src/tx/schema/ibcTransfer.ts
  packages/types/src/tx/schema/index.ts
  packages/types/src/tx/schema/shielded.ts
  packages/types/src/tx/schema/transfer.ts
  packages/types/src/tx/schema/tx.ts
  packages/types/src/tx/schema/unbond.ts
  packages/types/src/tx/schema/utils.ts
  packages/types/src/tx/types.ts
  packages/types/tsconfig.json
  packages/utils/src/helpers/index.ts
  yarn.lock
Labels: C - Refactoring

#331 fix: calculate toast props from toast type
  apps/namada-interface/src/slices/transfers.ts
Labels: C - Bug

#341 feat/340 - Implement logic for constructing Ledger signatures
  apps/extension/src/background/ledger/service.ts
  apps/extension/src/utils/index.ts
  packages/ledger-namada/dist/common.d.ts
  packages/ledger-namada/dist/common.js.map
  packages/ledger-namada/dist/namadaApp.js
  packages/ledger-namada/dist/processResponses.js
  packages/ledger-namada/dist/processResponses.js.map
  packages/ledger-namada/dist/types.d.ts
  packages/ledger-namada/dist/types.js
  packages/ledger-namada/dist/types.js.map
  packages/shared/lib/src/sdk/mod.rs
  packages/shared/lib/src/sdk/signature.rs
  packages/types/src/tx/schema/index.ts
  packages/types/src/tx/schema/signature.ts
  packages/types/src/tx/types.ts
Labels: T - Ledger HW, C - Feature

#339 feat/311 - Implement ledger integration improvements
  apps/extension/src/Approvals/Approvals.tsx
  apps/extension/src/Approvals/ApproveBond/ApproveBond.tsx
  apps/extension/src/Approvals/ApproveBond/index.ts
  apps/extension/src/Approvals/ApproveTransfer/ApproveTransfer.tsx
  apps/extension/src/Approvals/ApproveTransfer/ConfirmLedgerTransfer.tsx
  apps/extension/src/Approvals/ApproveTransfer/ConfirmTransfer.tsx
  apps/extension/src/Approvals/ApproveTransfer/index.ts
  apps/extension/src/Approvals/ApproveTx/ApproveTx.tsx
  apps/extension/src/Approvals/ApproveTx/ConfirmLedgerTx.tsx
  apps/extension/src/Approvals/ApproveTx/ConfirmTx.tsx
  apps/extension/src/Approvals/ApproveTx/index.ts
  apps/extension/src/Approvals/types.ts
  apps/extension/src/background/approvals/handler.ts
  apps/extension/src/background/approvals/init.ts
  apps/extension/src/background/approvals/messages.ts
  apps/extension/src/background/approvals/service.ts
  apps/extension/src/background/keyring/init.ts
  apps/extension/src/background/keyring/service.ts
  apps/extension/src/background/ledger/handler.ts
  apps/extension/src/background/ledger/init.ts
  apps/extension/src/background/ledger/messages.ts
  apps/extension/src/background/ledger/service.ts
  apps/extension/src/hooks/useQuery.tsx
  apps/extension/src/provider/InjectedNamada.ts
  apps/extension/src/provider/Namada.ts
  apps/extension/src/provider/Signer.ts
  apps/extension/src/provider/messages.ts
  apps/extension/src/utils/index.ts
  apps/namada-interface/src/schema/index.ts
  apps/namada-interface/src/slices/StakingAndGovernance/actions.ts
  apps/namada-interface/src/types/environment.d.ts
  packages/ledger-namada/dist/processResponses.js
  packages/ledger-namada/dist/processResponses.js.map
  packages/ledger-namada/dist/types.d.ts
  packages/ledger-namada/dist/types.js
  packages/ledger-namada/dist/types.js.map
  packages/shared/lib/src/sdk/mod.rs
  packages/shared/lib/src/sdk/signature.rs
  packages/shared/lib/src/sdk/tx.rs
  packages/types/src/namada.ts
  packages/types/src/signer.ts
  packages/types/src/tx/schema/index.ts
  packages/types/src/tx/schema/revealPK.ts
  packages/types/src/tx/schema/signature.ts
  packages/types/src/tx/types.ts
Labels: C - Refactoring, T - Wallet Core, T - Ledger HW, T - SDK

#348 Updating README.md for macOS
  README.md
  apps/extension/README.md
  packages/crypto/README.md
  packages/shared/README.md
Labels: C - Documentation
