Repository anoma/namada-interface, pull requests merged in 2023-01, with the labels that each got.

#189 feat: load accounts from metamask
  apps/namada-interface/src/services/integrations.tsx
  apps/namada-interface/src/slices/accounts.ts
  packages/chains/src/chains/ethereum.ts
  packages/chains/src/index.ts
  packages/integrations/package.json
  packages/integrations/src/Metamask.ts
  packages/integrations/src/index.ts
  yarn.lock
Labels: Wallet UI

#195 refactor/194 - Remove unused code
  packages/chains/tsconfig.json
  packages/crypto/lib/Cargo.lock
  packages/crypto/lib/Cargo.toml
  packages/crypto/lib/src/crypto/mod.rs
  packages/crypto/lib/src/crypto/scrypt.rs
  packages/crypto/src/__tests__/crypto.test.ts
  packages/utils/src/crypto/index.ts
  packages/utils/src/index.ts
Labels: C - Refactoring

#174 feat/141 - Prompt for password only when needed
  apps/extension/src/App/Accounts/AddAccount.tsx
  apps/extension/src/App/App.tsx
  apps/extension/src/App/Approvals/ApproveConnection.components.tsx
  apps/extension/src/App/Approvals/ApproveConnection.tsx
  apps/extension/src/App/Approvals/ApproveTx.components.tsx
  apps/extension/src/App/Approvals/ApproveTx.tsx
  apps/extension/src/App/Approvals/index.ts
  apps/extension/src/App/LockWrapper/LockWrapper.tsx
  apps/extension/src/App/Login/Login.tsx
  apps/extension/src/App/types.ts
  apps/extension/src/background/index.ts
  apps/extension/src/hooks/index.ts
  apps/extension/src/hooks/useAuth.tsx
  apps/extension/src/hooks/useQuery.tsx
  packages/chains/src/chains/namada.ts
Labels: C - Feature, Extension UI, E - Extension
